# If you do not have OpenSSL installed, update
# the following line to use "http://" instead
source 'https://rubygems.org'

gemspec

gem "middleman", "~>3.3.7"

gem 'middleman-sprockets'  # The best asset pipeline
gem 'middleman-livereload' # Save a file, see your browser reload

# For faster file watcher updates on Windows:
gem "wdm", "~> 0.1.0", :platforms => [:mswin, :mingw]

# Windows does not come with time zone data
gem "tzinfo-data", platforms: [:mswin, :mingw]

gem "pry"
